workflows:
  version: 2
  test_build:
    jobs:
      - test
      - build

version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: install package
          command: "npm install"
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run test
          command: "npm run test"

  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: build package
          command: "npm run build"
