workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two

version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run test
