workflows:
  version: 2
  test_build:
    jobs:
      - setup
      - test

version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: install package
          command: "npm install"
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: run test
          command: "npm run test"
