workflows:
  version: 2
  test_build:
    jobs:
      - build

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: install package
          command: "npm install"
      - run:
          name: run test
          command: "npm run test"
